-- ─── Brochure Categories Migration (MySQL) ──────────────────────────────────
INSERT INTO categories (name, slug, description, sort_order, is_active) VALUES
    ('Packaging for Bakery Products', 'packaging-for-bakery-products', 'We manufacture a complete range of premium bakery packaging designed to keep baked products fresh, safe, and visually appealing. Our product range includes cake boxes, pastry boxes, pizza boxes, cupcake boxes, cookie boxes, and takeaway packaging in a variety of sizes and designs. Made from high-quality food-grade materials, our packaging ensures durability, hygiene, and superior product protection. With fully customized printing and branding options, we create bakery packaging that enhances presentation and strengthens your brand identity.', 1, 1),
    ('Moulding Boxes', 'moulding-boxes', 'We also manufacture a wide range of premium-quality plastic food packaging containers using different moulds and designs. These boxes are ideal for sweets, bakery products, snacks, fruits, dry fruits, takeaway meals, and other food items. Made from food-grade material, they offer excellent clarity, durability, and a secure locking system to keep products fresh and protected. Available in various shapes and sizes, our containers provide practical, hygienic, and attractive packaging solutions for every business.', 2, 1),
    ('Luxury Sweet Boxes', 'luxury-sweet-boxes', 'We manufacture a comprehensive range of premium paper and rigid boxes designed to meet diverse packaging requirements. From mono cartons and corrugated boxes to luxury rigid gift boxes, every product is crafted with precision, durability, and superior finishing. Our customized packaging solutions combine functionality with premium aesthetics, making them ideal for every industry. Backed by advanced manufacturing and strict quality standards, we deliver packaging that enhances product protection, shelf appeal, and overall brand value.', 3, 1),
    ('Wrapping Papers', 'wrapping-papers', 'We offer a premium collection of wrapping papers for gift boxes, sweet boxes, and retail packaging. Available in customized designs, colors, and finishes, our wrapping papers enhance product presentation while adding a refined and luxurious appeal. Manufactured using high-quality materials and advanced printing techniques, they provide an elegant finish while ensuring durability and consistency. With complete customization options, we create wrapping papers that strengthen your brand identity and make every package more attractive and memorable.', 4, 1),
    ('Premium Paper Bag', 'premium-paper-bag', 'Our premium paper bags are crafted to enhance your brand while providing a sustainable packaging solution. Available in multiple sizes, paper qualities, and handle options, they are perfect for shopping, gifting, food, apparel, and luxury retail applications. With superior printing and complete customization, we create paper bags that leave a lasting impression while supporting an eco-friendly future. Every bag is designed to combine strength, style, and functionality, ensuring an exceptional customer experience.', 5, 1),
    ('Premium Wedding Boxes', 'premium-wedding-boxes', 'Celebrate every wedding with beautifully crafted "Indian Wedding (Bhaji) Boxes" designed to make every gift more memorable. Our collection includes premium boxes in a variety of sizes, styles, and elegant finishes, perfect for sweets, dry fruits, gifts, and wedding favors. Crafted with high-quality materials and attractive designs, these boxes add a touch of luxury to every celebration. We also offer customized wedding packaging to match your theme, colors, and branding requirements.', 6, 1),
    ('Ice Cream Packaging', 'ice-cream-packaging', 'We manufacture premium-quality Ice Cream Packaging designed to keep your products fresh, safe, and visually appealing. Our range includes paper ice cream cups, takeaway tubs, family packs, paper boxes, cone sleeves, and custom packaging solutions in various sizes. Made from food-grade materials with high-quality printing, our packaging is perfect for ice cream parlors, cafes, and dessert brands. We also offer fully customized designs to match your brand identity and packaging requirements.', 7, 1)
ON DUPLICATE KEY UPDATE 
    name = VALUES(name),
    description = VALUES(description),
    sort_order = VALUES(sort_order),
    is_active = VALUES(is_active);
